### ISSUE TITLE
Not compatible with latest Xamarin.iOS due to Microsoft.Bcl.Build dependency? 

### ISSUE THREAD

**Issue by chamons** [Microsoft/BingMapsSDSToolkit#2]
When attempting to use BingMapsSDSToolkit.1.0.3 with Xamarin.iOS, I get this nuget error:

Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Steps to reproduce:
- Install Xamarin Stack (https://gist.github.com/chamons/c72d74f2730d6c1d99bd06160eae65ac)
- New Xamarin.iOS Project
- Add Package -> BingMapsSDSToolkit.1.0.3

It does work with Xamarin.Mac Full profile but does not work with Modern for the same exact reason.

**Comment by rbrundritt** [comment]
Make sure that you have Xamarin Portable Class Library profiles for Xamarin.iOS installed before adding this package. This package is a portable class library.
