### ISSUE TITLE
Missing POI data in SDS public data sources

### ISSUE THREAD

**Issue by dpaulino** [Microsoft/BingMapsSDSToolkit#4]
Hi there, 

I have been exploring this SDS API since it can list the x closest entities from a given geopoint. I'm particularly interested in looking for grocery store entities from the NAVTEQNA data source (https://msdn.microsoft.com/en-us/library/hh478192.aspx). However, it seems that some stores are not available in this database. For instance, in Canada there is a chain of stores called "Real Canadian Superstore". This is not found in the database when using the following query
```
http://spatial.virtualearth.net/REST/v1/data/f22876ec257b474b82fe2ffcb8393150/NavteqNA/NavteqPOIs?spatialFilter=nearby({my location})&$filter=EntityTypeID%20eq%20'5400'&$select=EntityID,DisplayName,Latitude,Longitude,__Distance,AddressLine,Locality,CountryRegion&$top=6&key={bingMapsKey}
```

How would one go about getting the NAVTEQNA data source updated with new entity data? 

Cheers, 
Daniel

**Comment by rbrundritt** [comment]
This is a public API that is maintained by NAVTEQ. Any one can make a data source public and manage it themselves. It is unlikely that the NAVTEQ data source will be updated any time soon, however the Bing Maps team is planning on releasing some point of interest API's in 2018.
