### ISSUE TITLE
Class links in Readme lead to 400 error pages

### ISSUE THREAD

**Issue by aliziani** [microsoft/BingMapsSDSToolkit#6]
Hello guys,

I noticed that the link to class "GeocodeFeed" lead to 404.
The good link is : https://github.com/microsoft/BingMapsSDSToolkit/blob/master/Docs/ApiReference/GeocodeDataFlowApiReference.md#geocodefeed-class

Kr,
Ali

**Comment by IoTGirl** [comment]
I am not able to repro.  Please provide steps to see the 404.

**Comment by IoTGirl** [comment]
Closing - stale
